lo que llevaba hasta ahorita en mi otro repo
arturogonzalezp/elections2018-backend pull request #1
Opened 2018-01-22 16:52 UTC by GabrielAvilesR

kiuvo

2018-01-22 17:00 UTC, GabrielAvilesR reviewed
Esta bien padre todo. Me Approve

2018-01-22 17:00 UTC, gaboTruGomez approved these changes

2018-01-22 17:14 UTC, heyimcesar requested changes

2018-01-22 17:14 UTC, arturogonzalezp commented on LICENSE
> -MIT License
Deja el LICENSE en tu rama también

2018-01-22 17:14 UTC, arturogonzalezp commented on .gitignore
> -# Logs
El .gitignore que había puesto era el completo para proyectos de node.

2018-01-22 17:14 UTC, arturogonzalezp commented on README.md
> -# elections2018-backend
No borres el contenido del Readme, lo usaremos para documentación

2018-01-22 18:55 UTC, GabrielAvilesR commented on .gitignore
> -# Logs
okok sorry, solo borre todo y puse lo mio jeje

2018-01-22 19:01 UTC, GabrielAvilesR commented on README.md
> -# elections2018-backend
ya esta, tengo que hacer un nuevo pr?

2018-01-24 17:30 UTC, heyimcesar requested changes
Más cambios

2018-01-24 17:30 UTC, arturogonzalezp commented on README.md
> -# elections2018-backend
No, solo tienes que arreglarlo en esta rama y actualizarla con un push

2018-01-24 17:30 UTC, arturogonzalezp commented on package-lock.json
> +{
pon este archivo en el .gitignore

2018-01-25 15:02 UTC, heyimcesar approved these changes

2018-01-25 15:03 UTC, merged